apiVersion: v1
kind: ConfigMap
metadata:
  name: tasks-app
data:
  APP_UI_AUTH_DOMAIN: zitadel.${DOMAIN}
  APP_UI_AUTH_REDIRECT_URI: https://tasks-app.${DOMAIN}/ui/auth/callback
  APP_UI_TRUSTED_HOSTS: tasks-app.${DOMAIN}
  APP_EMAIL_NOTIFIER_ZITADEL_URL: https://zitadel.${DOMAIN}
  APP_EMAIL_NOTIFIER_SMTP_FROM_ADDRESS: no-reply@tasks-app.${DOMAIN}
