version: "3.9"

services:
  tasks-app:
    build: ../src
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    networks:
      - tasks-app
    depends_on:
      - postgres
      - nats
