services:
  tasks-app:
    build:
      context: ../../src
      args:
        GOARCH: amd64
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/tasks-app.env
    secrets:
      - source: root.crt
        target: /etc/tasks-app/certs/root.crt
      - source: app_user.creds
        target: /app_user.creds
    environment:
      - APP_SHARED_SERVICES=db:postgres,attachments:nats,messaging:nats
      - APP_SHARED_MODULES=ui
    networks:
      - tasks-app

  tasks-app-taskchecker:
    build:
      context: ../../src
      args:
        GOARCH: amd64
    image: tasks-app/tasks-app-taskchecker
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/tasks-app.env
    secrets:
      - source: root.crt
        target: /etc/tasks-app/certs/root.crt
      - source: app_user.creds
        target: /app_user.creds
    environment:
      - APP_SHARED_SERVICES=db:postgres,messaging:nats
      - APP_SHARED_MODULES=taskchecker
    networks:
      - tasks-app

  tasks-app-emailnotifier:
    build:
      context: ../../src
      args:
        GOARCH: amd64
    image: tasks-app/tasks-app-emailnotifier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/tasks-app.env
    secrets:
      - source: root.crt
        target: /etc/tasks-app/certs/root.crt
      - source: app_user.creds
        target: /app_user.creds
    environment:
      - APP_SHARED_SERVICES=messaging:nats
      - APP_SHARED_MODULES=emailnotifier:smtp
    networks:
      - tasks-app

secrets:
  root.crt:
    file: ./certs/root.crt
  app_user.creds:
    file: ./nats/nsc/keys/creds/tasks_app_operator/tasks_app_account/app_user.creds

networks:
  tasks-app:
    name: tasks-app
    external: true
