version: "3.9"

services:
  caddy:
    build: ../../infra/caddy
    image: tasks-app/caddy
    deploy:
      restart_policy:
        condition: on-failure
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    secrets:
      - source: root.key
        target: /etc/caddy/certs/root.key
      - source: root.crt
        target: /etc/caddy/certs/root.crt
    ports:
      - "443:443"
    networks:
      tasks-app:
        aliases:
          - www.tasks-app.com
          - auth.tasks-app.com
          - smtp.tasks-app.com

  zitadel:
    build: ../../infra/zitadel
    image: tasks-app/zitadel
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/zitadel.env
    ports:
      - "8080:8080"
    volumes:
      - ./zitadel/machinekey:/machinekey
    networks:
      - tasks-app
    depends_on:
      - postgres

  postgres:
    build: ../../infra/postgres
    image: tasks-app/postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - tasks-app

  postgres-migrate:
    build: ../../infra/postgres-migrate
    image: tasks-app/postgres-migrate
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/postgres-migrate.env
    networks:
      - tasks-app
    depends_on:
      - postgres

  nats-1:
    build: ../../infra/nats
    image: tasks-app/nats
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/nats.env
      - ./config/nats-1.env
    ports:
      - "4222:4222"
      - "8222:8222"
      - "9222:9222"
    volumes:
      - nats-1:/nats
    networks:
      - tasks-app

  nats-2:
    build: ../../infra/nats
    image: tasks-app/nats
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/nats.env
      - ./config/nats-2.env
    volumes:
      - nats-2:/nats
    networks:
      - tasks-app

  nats-3:
    build: ../../infra/nats
    image: tasks-app/nats
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/nats.env
      - ./config/nats-3.env
    volumes:
      - nats-3:/nats
    networks:
      - tasks-app

  nats-configure:
    build: ../../infra/nats-configure
    image: tasks-app/nats-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./config/nats-configure.env
    secrets:
      - source: admin_user.creds
        target: /admin_user.creds
    networks:
      - tasks-app
    depends_on:
      - nats-1
      - nats-2
      - nats-3

  smtp4dev:
    image: rnwood/smtp4dev:v3
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - smtp4dev:/smtp4dev
    networks:
      - tasks-app

configs:
  Caddyfile:
    file: ./config/Caddyfile

secrets:
  root.key:
    file: ./certs/root.key
  root.crt:
    file: ./certs/root.crt
  admin_user.creds:
    file: ./nats/nsc/keys/creds/tasks_app_operator/tasks_app_account/admin_user.creds

networks:
  tasks-app:
    name: tasks-app

volumes:
  postgres:
  nats-1:
  nats-2:
  nats-3:
  smtp4dev:
