version: "3.9"

services:
  tasks-app:
    hostname: tasks-app.com
    build: ../src
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SHARED_SERVICES=db:postgres,attachments:nats
      - APP_SHARED_MODULES=ui
    networks:
      - tasks-app

  tasks-app-backend:
    build: ../src
    image: tasks-app/tasks-app-backend
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SHARED_SERVICES=db:postgres,messaging:nats
      - APP_SHARED_MODULES=taskchecker,emailnotifier:null
    networks:
      - tasks-app
