version: "3.9"

services:
  tasks-app:
    build: ../src
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SERVICES=db:postgres
      - APP_MODULES=ui
    networks:
      - tasks-app
    depends_on:
      - postgres

  tasks-app-backend:
    build: ../src
    image: tasks-app/tasks-app-backend
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SERVICES=db:postgres,messaging:nats
      - APP_MODULES=taskchecker,emailnotifier:null
    networks:
      - tasks-app
    depends_on:
      - postgres
      - nats
