version: "3.9"

services:
  caddy:
    build: ../proxy/caddy
    image: tasks-app/caddy
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/caddy.env
    ports:
      - 8000:80
    networks:
      - tasks-app

  postgres:
    build: ../db/postgres
    image: tasks-app/postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - tasks-app

  postgres-migrations:
    build: ../db/postgres-migrations
    image: tasks-app/postgres-migrations
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/postgres-migrations.env
    networks:
      - tasks-app
    depends_on:
      - postgres

  nats:
    build: ../messaging/nats
    image: tasks-app/nats
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/nats.env
    ports:
      - 4222:4222
      - 8222:8222
      - 9222:9222
    volumes:
      - nats:/nats
    networks:
      - tasks-app

  nats-configure:
    build: ../messaging/nats-configure
    image: tasks-app/nats-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/nats-configure.env
    networks:
      - tasks-app
    depends_on:
      - nats

networks:
  tasks-app:
    name: tasks-app

volumes:
  postgres:
  nats:
