version: "3.9"

name: tasks-app

services:
  tasks-app:
    build: ../src
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    volumes:
      - ./certs/root.crt:/etc/tasks-app/certs/root.crt:ro
      - ./nats/nsc/keys/creds/tasks_app_operator/tasks_app_account/app_user.creds:/app_user.creds
      - ./nats/nsc/stores/tasks_app_operator/accounts/tasks_app_account/users/ui_user.jwt:/ui_user.jwt
    environment:
      - APP_SHARED_SERVICES=db:postgres,attachments:nats
      - APP_SHARED_MODULES=ui
    networks:
      - tasks-app

  tasks-app-taskchecker:
    build: ../src
    image: tasks-app/tasks-app-taskchecker
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    volumes:
      - ./certs/root.crt:/etc/tasks-app/certs/root.crt:ro
      - ./nats/nsc/keys/creds/tasks_app_operator/tasks_app_account/app_user.creds:/app_user.creds
    environment:
      - APP_SHARED_SERVICES=db:postgres,messaging:nats
      - APP_SHARED_MODULES=taskchecker
    networks:
      - tasks-app

  tasks-app-emailnotifier:
    build: ../src
    image: tasks-app/tasks-app-emailnotifier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    volumes:
      - ./certs/root.crt:/etc/tasks-app/certs/root.crt:ro
      - ./nats/nsc/keys/creds/tasks_app_operator/tasks_app_account/app_user.creds:/app_user.creds
    environment:
      - APP_SHARED_SERVICES=messaging:nats
      - APP_SHARED_MODULES=emailnotifier:null
    networks:
      - tasks-app

networks:
  tasks-app:
    name: tasks-app
    external: true
