version: "3.9"

name: tasks-app

services:
  tasks-app:
    build: ../src
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    volumes:
      - ./certs/root.crt:/etc/tasks-app/certs/root.crt:ro
    networks:
      - tasks-app

networks:
  tasks-app:
    name: tasks-app
    external: true
