version: "3.9"

name: tasks-app

services:
  tasks-app:
    build: ../src
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    volumes:
      - ./certs/root.crt:/etc/tasks-app/certs/root.crt:ro
    environment:
      - APP_SHARED_SERVICES=db:postgres,attachments:nats
      - APP_SHARED_MODULES=ui
    networks:
      - tasks-app

  tasks-app-backend:
    build: ../src
    image: tasks-app/tasks-app-backend
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SHARED_SERVICES=db:postgres,messaging:nats
      - APP_SHARED_MODULES=taskchecker,emailnotifier:null
    networks:
      - tasks-app

networks:
  tasks-app:
    name: tasks-app
    external: true
