version: "3.9"

services:
  tasks-app:
    build:
      context: ../src
      args:
        GOARCH: ${GOARCH}
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    secrets:
      - source: root.crt
        target: /etc/tasks-app/certs/root.crt
      - source: app_user.creds
        target: /app_user.creds
    environment:
      - APP_SHARED_SERVICES=db:postgres,attachments:nats
      - APP_SHARED_MODULES=ui
    networks:
      - tasks-app

  tasks-app-backend:
    build:
      context: ../src
      args:
        GOARCH: ${GOARCH}
    image: tasks-app/tasks-app-backend
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    secrets:
      - source: root.crt
        target: /etc/tasks-app/certs/root.crt
      - source: app_user.creds
        target: /app_user.creds
    environment:
      - APP_SHARED_SERVICES=db:postgres,messaging:nats
      - APP_SHARED_MODULES=taskchecker,emailnotifier:null
    networks:
      - tasks-app

secrets:
  root.crt:
    file: ./certs/root.crt
  app_user.creds:
    file: ./nats/nsc/keys/creds/tasks_app_operator/tasks_app_account/app_user.creds

networks:
  tasks-app:
    name: tasks-app
    external: true
