CREATE TABLE task (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id varchar(200) NOT NULL,
    name varchar(200) NOT NULL,
    expires_at timestamptz,
    expiring_info_at timestamptz,
    expired_info_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz,
    completed_at timestamptz
);

CREATE TABLE attachment (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id integer REFERENCES task(id) ON DELETE CASCADE,
    file_name varchar(200) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz
);
