version: "3.9"

services:
  tasks-app:
    build: ../src
    image: tasks-app/tasks-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SHARED_SERVICES=db:postgres
      - APP_SHARED_MODULES=ui
    networks:
      - tasks-app
    depends_on:
      - postgres

  tasks-app-taskchecker:
    build: ../src
    image: tasks-app/tasks-app-taskchecker
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SHARED_SERVICES=db:postgres,messaging:nats
      - APP_SHARED_MODULES=taskchecker
    networks:
      - tasks-app
    depends_on:
      - postgres
      - nats

  tasks-app-emailnotifier:
    build: ../src
    image: tasks-app/tasks-app-emailnotifier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    env_file:
      - ../config/dev/tasks-app.env
    environment:
      - APP_SHARED_SERVICES=messaging:nats
      - APP_SHARED_MODULES=emailnotifier:null
    networks:
      - tasks-app
    depends_on:
      - nats
