apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-app
spec:
  template:
    spec:
      containers:
        - name: tasks-app-ui
          image: ${IMAGE}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
          env:
            - name: APP_SHARED_MODULES
              value: ui
            - name: APP_SHARED_SERVICES
              value: db:postgres,attachments:nats,messaging:nats
            - name: SSL_CERT_FILE
              value: /etc/nats/ca.crt
          envFrom:
            - configMapRef:
                name: tasks-app
            - secretRef:
                name: tasks-app
          volumeMounts:
            - name: nats-tls
              readOnly: true
              mountPath: /etc/nats/ca.crt
              subPath: ca.crt
            - name: nats-app-cred
              readOnly: true
              mountPath: /app.cred
              subPath: app.cred

        - name: tasks-app-taskchecker
          image: ${IMAGE}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: APP_SHARED_MODULES
              value: taskchecker
            - name: APP_SHARED_SERVICES
              value: db:postgres,messaging:nats
            - name: SSL_CERT_FILE
              value: /etc/nats/ca.crt
          envFrom:
            - configMapRef:
                name: tasks-app
            - secretRef:
                name: tasks-app
          volumeMounts:
            - name: nats-tls
              readOnly: true
              mountPath: /etc/nats/ca.crt
              subPath: ca.crt
            - name: nats-app-cred
              readOnly: true
              mountPath: /app.cred
              subPath: app.cred

        - name: tasks-app-emailnotifier
          image: ${IMAGE}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: APP_SHARED_MODULES
              value: emailnotifier:smtp
            - name: APP_SHARED_SERVICES
              value: messaging:nats
            - name: SSL_CERT_FILE
              value: /etc/nats/ca.crt
          envFrom:
            - configMapRef:
                name: tasks-app
            - secretRef:
                name: tasks-app
          volumeMounts:
            - name: nats-tls
              readOnly: true
              mountPath: /etc/nats/ca.crt
              subPath: ca.crt
            - name: nats-app-cred
              readOnly: true
              mountPath: /app.cred
              subPath: app.cred
