apiVersion: v1
kind: Secret
metadata:
  name: tasks-app
stringData:
  POSTGRES_POSTGRES_CONNECTIONSTRING: postgres://postgres:S3c_r3t!@postgresql.examples.svc.cluster.local:5432/postgres?sslmode=disable&search_path=public
  POSTGRES_TASKS_APP_CONNECTIONSTRING: postgres://postgres:S3c_r3t!@postgresql.examples.svc.cluster.local:5432/tasks_app?sslmode=disable&search_path=public
  APP_SHARED_POSTGRES_CONNECTION_STRING: postgres://postgres:S3c_r3t!@postgresql.examples.svc.cluster.local:5432/tasks_app?sslmode=disable
  APP_SHARED_NATS_ACCOUNT_SEED: ${NATS_ACCOUNT_SEED}
  APP_UI_AUTH_ENCRYPTION_KEY: secret12secret12
  APP_EMAIL_NOTIFIER_ZITADEL_PAT: ${ZITADEL_EMAIL_NOTIFIER_PAT}
  APP_EMAIL_NOTIFIER_SMTP_PASSWORD: empty
